[package]
version = "0.1.0"
name = "zkvdb-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.1" }
zkvdb-lib = { path = "../lib" }
